# select the dotnet image
FROM ubuntu:20.04

RUN mkdir /build_cms
RUN mkdir /build_cms/sys

# copy over the cms
COPY ./build_cms/app/build_cms /build_cms/sys
COPY ./build_cms/app/.htaccess /build_cms/.htaccess
COPY ./build_cms/app/index.php /build_cms/index.php
COPY ./build_cms/docker/TD_dbExport/data/build-cms.json /build_cms/db.json

# copy the installer
COPY ./build_cms/php_installer/install.php /build_cms/installer/index.php

# remove the plugins from the system
RUN rm -fr /build_cms/sys/plugins && \
    rm -fr /build_cms/sys/build_cms_system/system && \
    rm -f /build_cms/sys/build_cms_system/data/load_system_plugins.json

# copy the plugins
COPY ./build_cms/app/build_cms/plugins /build_cms/plugins

# copy the system plugins
COPY ./build_cms/app/build_cms/build_cms_system/system /build_cms/system-plugins

# create and go to compiler dir
RUN mkdir /compiler
WORKDIR /compiler

# update
RUN apt-get update && apt-get upgrade -y

# install wget
RUN apt-get install wget -y

# get ms repo
RUN wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    rm -fr packages-microsoft-prod.deb

# install dotnet
RUN apt-get update && \
    apt-get install -y apt-transport-https && \
    apt-get update && \
    apt-get install -y dotnet-sdk-5.0 && \
    rm -fr /var/cache/*

# Required inside Docker, otherwise file-change events may not trigger
ENV DOTNET_USE_POLLING_FILE_WATCHER=true

CMD [ "dotnet", "watch", "run", "--no-restore", "--urls", "http://0.0.0.0:5000" ]