FROM ubuntu:20.04

# Update base image
RUN apt-get update -y
RUN apt-get upgrade -y

# set time sone
ENV timezone=UTC
RUN echo $timezone > input.txt
RUN apt-get install -y tzdata < input.txt
RUN rm input.txt

# Install PHP
RUN apt-get install php7.4-mysql -y
RUN apt-get install php7.4-cli -y

CMD php /TD_dbExport/backup.php